### ISSUE TITLE
Arduino Pro mini?

### ISSUE THREAD

**Issue by H1ghTech** [spacehuhn/wifi_ducky#1]
Just wondering if this could work if you add a usb with d+ d- + - 
#1

**Comment by tobozo** [comment]
Depending on the chosen model (pro mini 3.3v or 5v) I wonder if you'll need a logic level converter between the arduino and the ESP or between the arduino and the USB.

**Comment by H1ghTech** [comment]
Ok I got a 5v one but I have a level shifter

**Comment by tobozo** [comment]
I'll try later tonight, I have both 5v and 3.3v model, I'm very interested by the results of your tests

**Comment by H1ghTech** [comment]
And how do i wire the usb jack?😂

**Comment by spacehuhn** [comment]
you need an ATmega32u4 the Pro mini doesn't use that microcontroller.

**Comment by spacehuhn** [comment]
But you could use a Arduino Pro micro. You'll need the 3.3V version yes, or use a voltage regulator.

**Comment by H1ghTech** [comment]
What is the difference between the two microcontrollers?

**Comment by spacehuhn** [comment]
one can talk USB the other not.

**Comment by H1ghTech** [comment]
Aren't there any library's for usb ?

**Comment by tobozo** [comment]
[They're not that expensive](https://www.aliexpress.com/item/Mini-Leonardo-Pro-Micro-ATmega32U4-5V-16MHz-Module-For-Arduino-Best-Quality/32284746884.html)

**Comment by H1ghTech** [comment]
I didn't was that they are expensive lol

**Comment by tobozo** [comment]
edited my comment, some of it got lost in transit

**Comment by H1ghTech** [comment]
Lol

**Comment by tobozo** [comment]
Just stumbled upon [this](https://github.com/cnlohr/espusb) and it looks like the ESP8266 can act as a low speed USB if you can bother to lose ESP8266AsyncWebServer and use SDK 1.5.x or earlier

**Comment by spacehuhn** [comment]
haha @tobozo you haven't read the readme, right? Because I linked exectly that project. 😄

**Comment by tobozo** [comment]
Your readme says "The Latest SDK" while espusb's readme says "You cannot use SDKs newer than 1.5.X" now I'm confused

**Comment by tobozo** [comment]
Also why are you using an arduino when espusb can have the ESP to act as a host ?

**Comment by spacehuhn** [comment]
### How it works

[...]

Although the ESP8266 is awesome, it doesn't have native USB, which means it can't act as a keyboard :(  
([cnlohr](https://github.com/cnlohr) made a cool project on this and added a USB stack himself: https://github.com/cnlohr/espusb. The problem with that is, that it isn't compatible with the current SDK version, also I wanted to use Arduino to make it more user friendly.)  

Here comes the ATmega32u4 into play!  
[...]

**Comment by tobozo** [comment]
Ok danke stupid me lol

So in order to use this librarty one would need to use two ESPs, one for the logic+wifi, the other to act as a USB host, and that would be:

- An IDE mess
- Not user friendly
- Interferences
- Pointless

thank you sir!
