### ISSUE TITLE
No Backslash "\" possible in non-US Keyboard 

### ISSUE THREAD

**Issue by tomisboy** [spacehuhn/wifi_ducky#18]
There is no way to write a backslash,  for example in german Keyboard-Layout

I tested several thinks 

CTRL ALT ß 
did not work 
however 
CTRL ALT q 
writes the right character "@"
same with CTRL SHIRT e
which writes "€"

unfortunately alt Codes also did not work 
i tried it with 
ALT 9 2
did not work either

**Comment by ahhashim** [comment]
Try Alt Gr + ß

**Comment by tomisboy** [comment]
Ducky Script does not know "ALTGR"
https://github.com/hak5darren/USB-Rubber-Ducky/wiki/Duckyscript

**Comment by ahhashim** [comment]
I don't know if this would help, but maybe instead of KEY_LEFT_ALT try KEY_RIGHT_ALT. Im not sure if it would be the same though.

**Comment by ahhashim** [comment]
I haven't tried it on an actual Arduino board, but it compiles without errors in the Arduino IDE.

**Comment by tomisboy** [comment]
I put the Code in the website (192.168.4.1)
But no KEY_RIGHT_ALT does still not work :(

**Comment by spacehuhn** [comment]
OK yeah keyboard layout issues aren't really code issues, but I will look what I can do.
It's correct that at the moment there is no ALT KEY RIGHT or something implemented.
There is still a way to print that backslash, I did it before using the German keyboard layout. I'll do some tests!

Thanks for letting me know.

**Comment by tomisboy** [comment]
Thank you very much and keep up your great work:)
I really appreciate all the stuff you upload and create

**Comment by spacehuhn** [comment]
Ok so I think it was with the english keyboard library that I could print a backslash with a trick.
But yes I can't see how to do it with the German layout installed on the Arduino.

I will add the ALT-RIGHT key with the next update! (and also the ALT codes for windows)

**Comment by tomisboy** [comment]
Awesome, thank you very much

**Comment by keviiin38** [comment]
I had the same problem with the backslash, I solved it in my own issue on the Arduino forum at this address : http://forum.arduino.cc/index.php?topic=474156.0 
Hope you'll get it working !
