### ISSUE TITLE
command SPACE not working

### ISSUE THREAD

**Issue by joaquinsalih** [spacehuhn/wifi_ducky#21]
I dont know if only i have this issue but everytime i execute the SPACE command it inputs S instead of  spacebar. Does anybody know a fix?

**Comment by tomisboy** [comment]
SPACE is working with my Setup ? 
Are you sure you typed it correctly

**Comment by joaquinsalih** [comment]
Yes i tried several times on live execute and per script

**Comment by joaquinsalih** [comment]
I simply needed to reflash the wifi module
