### ISSUE TITLE
Broken link small update 

### ISSUE THREAD

**Issue by Labzz** [spacehuhn/wifi_ducky#33]
Noticed that the SPIFFS link was broken sadly enough :D 

How it works
The ESP8266 is a popular Wi-Fi chip used in a lot of projects. Because it's cheap, small and has its own file system (**_SPIFFS_**), it's perfect for enabling an easy remote connection and holding Ducky Script payloads.

**Comment by spacehuhn** [comment]
Oh yeah Espressif updated their documentation.
I fixed it now 70ce9b6c19722514ba4d34279f888102d8a9d788

Thanks for letting me know :)
