### ISSUE TITLE
Would this prebuild module work the same?

### ISSUE THREAD

**Issue by JeromeLC** [spacehuhn/wifi_ducky#8]
It appears to have the same hardware from what I can tell
http://tiny.cc/cactusmicor

**Comment by minkione** [comment]
It should be compatible 99%, since has same hw (Atmega 32u4 & ESP8266).
Didn't try WiFi_Ducky yet, but here a similar project [1]
The hardware prototype of WHID was based on a cactus micro rev2 ;)

[1] https://github.com/whid-injector/WHID/tree/master/sketches/cactus_micro_rev2

**Comment by spacehuhn** [comment]
It is compatible 👍
