### ISSUE TITLE
Seeking Clarification-Project Working Great!

### ISSUE THREAD

**Issue by B4UC2FAR** [spacehuhn/wifi_ducky#84]
This is the third of your projects I have built and would like to say thanks for sharing and for taking the time to support them. I am looking for clarification where you mention connecting to 192.168.4.1/update to load the .bin file. Is this .bin file you are referring to an actual ducky script being uploaded from another source besides the live execute window or is this .bin file you are referring to an actual update for the ESP8266 SDK such as was flashed onto it in the beginning steps? Thanks in advance for your time.

**Comment by Mr-iX** [comment]
The update section is for flashing a new firmware to the ESP. 
When you want to upload a Ducky script, you can do that on the scripts webpage:
![b91848bc-75d0-4b51-a962-866a0d37ff80](https://user-images.githubusercontent.com/25360303/31319990-3ecd5be0-ac6d-11e7-966f-558ea6624262.jpeg)

**Comment by B4UC2FAR** [comment]
Thanks for the clarification. It’s handy that the firmware can be updated from the browser as additional features are added.
