### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by beezTEM** [spacehuhn/wifi_ducky#9]
### Background
Found [this](https://www.adafruit.com/products/3156) when going through adafruit.
### The Question
Would it work instead of having to put together your own ducky? (prebuilt)

I am only asking this as I don't completely understand the requirements for this project, if it doesn't work, is there a prebuilt board that would work?

**Comment by spacehuhn** [comment]
No this doesn't have the ATmega32u4 and not the ESP8266 which is required.
The only prebuild board available would be this: http://wiki.aprbrother.com/wiki/Cactus_Micro_Rev2
